---
# tasks file for nginx

- name: Instalacao NGINX
  yum: name=nginx.x86_64 state=latest

- name: Habilita inicializacao
  command: chkconfig nginx on

- name: Cria Diretorio SSL
  command:  mkdir -p /etc/nginx/ssl

- name: Cria certificados Auto-Assinados SSL
  command: openssl req -new -nodes -x509 -subj "/C=BR/ST=Minas Gerais/L=Uberlandia/O=IT/CN={{ansible_fqdn}}" -days 3650 -keyout /etc/nginx/ssl/server.key -out /etc/nginx/ssl/server.crt -extensions v3_ca creates=/etc/nginx/ssl/server.crt

# Configura Proxy Reverso NGINX
- copy: src=files/nginx.conf dest=/etc/nginx/ owner=root group=root mode=0644

- name: Restart NGINX
  command: /etc/init.d/nginx restart

