---
# tasks file for mongodb

# Copia repositorio MongoDB
- copy: src=files/mongodb.repo dest=/etc/yum.repos.d/ owner=root group=root mode=0644

# Pacotes de Instalacao do MongoDB
- name: Instalacao do MongoDB
  yum: pkg={{item}} state=installed
  with_items:
   - mongo-10gen
   - mongo-10gen-server
   - pymongo

- name: Start MongoDB
  command: service mongod restart
# Criar database mongoDB


- name: Copia script para criacao do Banco
  copy: src=files/create-db.js dest=/tmp/

- name: Script de Criacao do Banco
  shell: mongo /tmp/create-db.js

# Nao cria o usuario
#- mongodb_user: database=ZupDB name=userzup password=123mudar roles='userAdminAnyDatabase' state=present


